### ISSUE TITLE
Reason for credit

### ISSUE THREAD

**Issue by simonfranz** [faustbrian/Laravel-Rewardable#9]
Hi there

In most cases there is a model-relation to a credit. For example if someone likes an post of a user the creator of the post gets 1 credit because of the like on the post, therefore the credit should have a relation to an eloquent model.

Somthing like:

```
$table->morphs('reasonable');
```

Also I noticed you have removed the documentation in one of your last commits, is there a special reason for this?

**Comment by DraperStudio** [comment]
Not really getting what you want but you can send a PR with improvements so I can better see what you mean.

Docs re-added for now, removed them because I am writing proper docs with examples.

**Comment by simonfranz** [comment]
Hopefully this does clear out the idea behind.

User A created a Post Z
User B likes Post Z
User A gets a Credit.
The Credit should have a reference back to Post Z so User A can see why he got a new Credit.
